### ISSUE TITLE
8: En tant que créateur et joueur, je souhaite avoir un tchat collectif afin de pouvoir communiquer.

### ISSUE THREAD

**Issue by Austreelis** [Austreelis/WebsiteWhereYouAreTheHero#12]
### Description

```
- Le-a joueur-se
- doit pouvoir utiliser un tchat 
- afin de pouvoir communiquer avec les autres joueur-se-s
```

### Estimation: `21`

Cette tâche requiert de mettre en place un système potentiellement complexe, avec une latence faible et le support d'un traffic conséquent. Nous avons donc estimé sa difficulté à élevée.

### Développeur-se

La développeuse responsable de cette tâche est Morgane Leclerc (a.k.a. @Austreelis).

### Reviewer

La personne en charge de la vérification sera Simon Nolf (a.k.a. @simonNolf).

### Prérequis

- [ ] Pouvoir jouer à une partie

### Technical Tasks

- [x] Création d'un serveur capable d'écouter/diffuser des messages sur des websockets (#32).
- [x] Ajout d'un mécanisme d'envoie et réception de messages pour les Clients (#32).
- [x] Gestion de l'identité dans les messages et leur affichage (#32).
- [x] Attribution d'une identité unique par les joueur-se-s (#38)
- [x] Gestion d'un nombre arbitraire de Joueur-se-s (#39).
- [x] Documentation du protocol utilisé pour l'échange de messages (#32).
- [ ] Ajouts de tests unitaires pour l'implémentation du protocol (#36).
- [ ] Ajout de tests des critères d'acceptation.

### Critères d'acceptation

- [x] Les Joueur-se-s peuvent s'attribuer une identité.
- [x] Les Joueur-se-s ne peuvent pas communiquer sans s'être attribuer une identité.
- [x] Les Joueur-se-s peuvent envoyer des messages à tout les Joueur-se-s.
- [x] Les Joueur-se-s peuvent identifier le-a Joueur-se ayant envoyé chacun des messages.
- [x] Au moins 8 Joueur-se-s peuvent participer à une même partie.
- [x] Les messages envoyé les plus récemment sont toujours affiché si le-a Joueur-se-s ne prend pas d'actions.

> TODO: Ces critères d'acceptation sont décris plus précisément et testé avec [`cucumber.js`](https://cucumber.io/tools/cucumber-open/), voir [`features/us8.feature` tests](https://github.com/Austreelis/Dev-Web-2022/blob/main/tests/integration/gherkin/us8.feature)

### maquette/schéma

![simple chatmockup](https://github.com/Austreelis/Dev-Web-2022/raw/pages/blobs/screenshot_1.png)

**Comment by Austreelis** [comment]
Related: #34

**Comment by Austreelis** [comment]
Apart from testing, this US is considered completely implemented :tada:
